sequenceDiagram
  participant Desarrollador as Desarrollador
  participant IDP as IDP
  participant GitHubOrquestator as GitHubOrquestator
  participant GitHubPrincipal as GitHubPrincipal
  participant TerraformCloud as TerraformCloud
  participant Jira as JiraTicketManager
  participant Azure as Azure

  Desarrollador ->> IDP: Solicitar las plantillas disponibles
  IDP -->> Desarrollador: Enviar lista de plantillas y valores necesarios
  Desarrollador ->> IDP: Elegir plantilla e ingresar valores
  IDP ->> IDP: Solicita aprobacion de ejecucion al LT
  IDP ->> GitHubOrquestator: Ejecuta pipeline creacion componente <br>
  GitHubOrquestator ->> GitHubPrincipal: Solicita latest de repo(clone)
  GitHubPrincipal -->> GitHubOrquestator: Envia codigo
  GitHubOrquestator ->> GitHubPrincipal: crea rama nueva <br>
  GitHubOrquestator ->> GitHubOrquestator: Genera template
  GitHubOrquestator ->> GitHubPrincipal: Envia template con nuevo codigo
  GitHubOrquestator ->> GitHubPrincipal: Genera PR
  GitHubPrincipal ->> Jira: Envia notificacion PR
  Jira -->> GitHubPrincipal: Aprueba PR
  GitHubPrincipal ->> TerraformCloud: lanza plan/apply <br>
  TerraformCloud ->> TerraformCloud: Auto apply
  TerraformCloud ->> Azure: Despliega componente


